[build]
rustflags = ["-C", "target-cpu=native", "-C", "target-feature=+aes,+avx2,+vaes,+ssse3", "--cfg", "aes_backend=\"avx256\""]
# add feature specified by the aes docs: https://docs.rs/aes/0.9.2/aes/#x86x86_64-intrinsics-aes-ni-and-vaes